---
# Based on https://blog.ruanbekker.com/blog/2020/02/04/run-kubernetes-k3s-as-a-service-container-on-drone-ci/
kind: pipeline
type: docker
name: gen-crd-bundles

platform:
  os: linux
  arch: amd64

steps:
  - name: wait-for-k3s
    image: alpine
    commands:
      - sleep 30

  - name: prepare-k3s-kubeconfig
    image: alpine
    volumes:
      - name: k3s-kubeconfig
        path: /k3s-kubeconfig
    detach: false
    commands:
      - sed -i -e "s/127.0.0.1/k3s/g" /k3s-kubeconfig/kubeconfig.yaml

  - name: download-crds
    image: bitnami/jsonnet:latest
    commands:
      - jsonnet -m . -S ./autogen.jsonnet
      - sh ./runme.sh

  - name: apply CRDs
    image: tanka:0.13
    volumes:
      - name: k3s-kubeconfig
        path: /tmp
    environment:
      KUBECONFIG: /tmp/kubeconfig.yaml
    commands:
      - tk apply . --dangerous-auto-approve

services:
  - name: k3s
    image: rancher/k3s:v1.19.5+k3s1
    privileged: true
    command:
      - server
    environment:
      K3S_KUBECONFIG_OUTPUT: /k3s-kubeconfig/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: 777
    volumes:
      - name: k3s-kubeconfig
        path: /k3s-kubeconfig
    ports:
      - 6443

volumes:
- name: k3s-kubeconfig
  temp: {}
